var aws = require('aws-sdk');
aws.config.update({ region: 'sa-east-1' });
var acm = new aws.ACM({apiVersion: '2015-12-08'});
var route53 = new aws.Route53();
var cloudfront = new aws.CloudFront({apiVersion: '2017-03-25'});
var async = require("async");

var dataRequested = null;
var dataHostedZone = null;
var dataHostedZoneValidationProperties = null;
var dataCloudfrontCallback = null;

exports.handler = (event, context, callback) =>  { //""
    console.log(event.DomainName); 

    async.waterfall([
        GetAndValidateRoute53Existence,
        RequestCertificate,
        AddTagToCertificate,
        DescribeCertificateToGetDNSProperties,
        RegisterCNAMEonRoute53,
        CreateDistribution,
        ChangeRoute53ARecordToCF
    ], function (err) {
        if (err) {
            callback(err);
        }
        callback(null, 'Works!');
    });    
};

function ChangeRoute53ARecordToCF() {
    
    var params = {
        ChangeBatch: {
            Changes: [
               {
                   Action: "UPSERT", 
                   ResourceRecordSet: {
                       Name: event.DomainName, 
                       ResourceRecords: [
                          {
                              Value: dataCloudfrontCallback.DomainName //like d19827391.cloudfront.com
                          }
                       ], 
                       TTL: 60, 
                       Type: "A"
                   }
               }
            ], 
            Comment: "WebServer on ElasticBeanstalk. This came from Lucas Schoch's Lambda."
        }, 
        HostedZoneId: dataHostedZone.Id
    };
    route53.changeResourceRecordSets(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            callback(null);            
        }                
    });
}

function CreateDistribution() {
    var date = new Date();
    var current_hour = date.getHours();
    var params = {
        DistributionConfigWithTags: {
            DistributionConfig: { 
                CallerReference: event.DomainName + ' - ' + current_hour, /* -----------------------------------------------required */
                Comment: 'Generated by Lambda - SSL - WebSites WM Platform', 
                DefaultCacheBehavior: { /* required */
                    ForwardedValues: { /* required */
                        Cookies: { /* required */
                            Forward: 'all', /* required */
                        },
                        QueryString: true, /* required */
                    },
                    MinTTL: 0, /* required */
                    TargetOriginId: 'ELB-lb-MY-LB-FROM-ELASTICBEANSTALK', /* required */
                    TrustedSigners: { /* required */
                        Enabled:  false, /* required */
                        Quantity: 0, /* required */                       
                    },
                    ViewerProtocolPolicy: 'redirect-to-https', /* required */
                    AllowedMethods: {
                        Items: [ /* required */
                          'GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE',
                          /* more items */
                        ],
                        Quantity: 7, /* required */
                        //CachedMethods: {
                        //    Items: [ /* required */
                              
                        //      /* more items */
                        //    ],
                        //    Quantity: 0 /* required */
                        //}
                    },
                    Compress: false,
                    DefaultTTL: 86400,
                    MaxTTL: 31536000,
                    SmoothStreaming: false
                },
                Enabled: true, /* required */
                Origins: { /* required */
                    Quantity: 1, /* required */
                    Items: [
                      {
                          DomainName: 'ELB-lb-MY-LB-FROM-ELASTICBEANSTALK.sa-east-1.elb.amazonaws.com', /* required */
                          Id: 'ELB-lb-MY-LB-FROM-ELASTICBEANSTALK', /* required */
                          //CustomHeaders: {
                          //    Quantity: 0, /* required */
                          //    Items: [                                
                          //      /* more items */
                          //    ]
                          //},
                          CustomOriginConfig: {
                              HTTPPort: 80, /* required */
                              HTTPSPort: 443, /* required */
                              OriginProtocolPolicy: 'http-only', /* required */
                              OriginKeepaliveTimeout: 5,
                              OriginReadTimeout: 30,
                              OriginSslProtocols: {
                                  Items: [ /* required */
                                    'TLSv1', 'TLSv1.1', 'TLSv1.2'
                              /* more items */
                                  ],
                                  Quantity: 3 /* required */
                              }
                          },
                          OriginPath: ''
                      },
                /* more items */
                    ]
                },
                Aliases: {
                    Quantity: 2, /* required */
                    Items: [
                      '*.'+ event.DomainName, event.DomainName,
                      /* more items */
                    ]
                },
                CacheBehaviors: {
                    Quantity: 1, /* required */
                    Items: [
                      {
                          ForwardedValues: { /* required */
                              Cookies: { /* required */
                                  Forward: 'all', /* required */
                              },
                              QueryString: true , /* required */
                              
                          },
                          MinTTL: 0, /* required */
                          PathPattern: '*', /* required */
                          TargetOriginId: 'ELB-lb-MY-LB-FROM-ELASTICBEANSTALK', /* required */
                          TrustedSigners: { /* required */
                              Enabled: false, /* required */
                              Quantity: 0, /* required */
                          },
                          ViewerProtocolPolicy: 'redirect-to-https', /* required */
                          AllowedMethods: {
                              Items: [ /* required */
                                'GET' , 'HEAD' , 'POST' , 'PUT' , 'PATCH' , 'OPTIONS' , 'DELETE',
                                /* more items */
                              ],
                              Quantity: 7, /* required */
                              //CachedMethods: {
                              //    Items: [ /* required */
                              //      GET | HEAD | POST | PUT | PATCH | OPTIONS | DELETE,
                              //      /* more items */
                              //    ],
                              //    Quantity: 0 /* required */
                              //}
                          },
                          Compress: false,
                          DefaultTTL: 86400,
                          MaxTTL: 31536000,
                          SmoothStreaming: false
                      },
                      /* more items */
                    ]
                },
                HttpVersion: 'http2',
                IsIPV6Enabled: true,
                PriceClass: 'PriceClass_All',
                ViewerCertificate: {
                    ACMCertificateArn: dataRequested.CertificateArn,
                    CloudFrontDefaultCertificate: false,
                    MinimumProtocolVersion: 'TLSv1.1_2016',
                    SSLSupportMethod: 'sni-only'
                }
            },
            Tags: { /* required */
                Items: [
                  {
                      Key: 'Name', /* required */
                      Value: event.DomainName
                  },
                  /* more items */
                ]
            }
        }
    };
    cloudfront.createDistributionWithTags(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            dataCloudfrontCallback = data;
            callback(null);            
        }       
    });
}

function RegisterCNAMEonRoute53() {
    var params = {
        ChangeBatch: {
            Changes: [
               {
                   Action: "CREATE", 
                   ResourceRecordSet: {
                       Name: dataHostedZoneValidationProperties.Name,
                       ResourceRecords: [
                          {
                              Value: dataHostedZoneValidationProperties.Value
                          }
                       ], 
                       TTL: 60, 
                       Type: dataHostedZoneValidationProperties.Type
                   }
               }
            ], 
            Comment: "Certificate Manager Created by Lucas Schoch's Lambda. :)"
        }, 
        HostedZoneId: dataHostedZone.Id
    };
    route53.changeResourceRecordSets(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            callback(null);            
        }       
    });
}

function DescribeCertificateToGetDNSProperties() {
    var params = {
        CertificateArn: dataRequested.CertificateArn 
    };
    acm.describeCertificate(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);       
            dataHostedZoneValidationProperties = data.Certificate.DomainValidationOptions[0].ResourceRecord;//contem Name - Type - Value  
            callback(null);            
        }       
    });
}

function GetAndValidateRoute53Existence() {
    var params = {
        DNSName: event.DomainName
    };
    route53.listHostedZonesByName(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            if (data.HostedZones[0] !== 'undefined') {
                dataHostedZone = data.HostedZones[0];
                callback(null);
            }
            else {
                callback('HostedZone não existente no Route53');
            }
        }
    });
}

function RequestCertificate() {
    var params = {
        DomainName: event.DomainName, /* required */
        SubjectAlternativeNames: [
          '*.'+event.DomainName
        ],
        ValidationMethod: 'DNS'
    };
    acm.requestCertificate(params, function(err, data) {
        if (err) {
            console.log(err, err.stack); // an error occurred
            callback(err);
        }
        else     {
            dataRequested = data;
            console.log(data);    
            callback(null);
        }
    });
}

function AddTagToCertificate() {
    var params = {
        CertificateArn: dataRequested.CertificateArn, /* required */
        Tags: [ /* required */
          {
              Key: 'Name', /* required */
              Value: event.DomainName
          },
          /* more items */
        ]
    };
    acm.addTagsToCertificate(params, function(err, data) {
        if (err) {
            console.log(err, err.stack); // an error occurred
            callback(err);
        }
        else{
            console.log(data);           // successful response
            callback(null);
        }
    });
}
