var aws = require('aws-sdk');
aws.config.update({ region: 'us-east-1' });
var acm = new aws.ACM({apiVersion: '2015-12-08'});
var route53 = new aws.Route53();
var cloudfront = new aws.CloudFront({apiVersion: '2017-03-25'});
var async = require("async");
var sleep = require('system-sleep');

var dataRequested = null;
var dataHostedZone = null;
var dataHostedZoneValidationProperties = null;
var dataCloudfrontCallback = null;
var event = null;

exports.handler = (eventt, context, callback)  => {
    console.log("-------------------------Starting Function-------------------------"); 
event = eventt;
console.log(event.HostedZoneId); 


async.waterfall([
    GetAndValidateRoute53Existence,
    RequestCertificate,
    AddTagToCertificate, 
    DescribeCertificateToGetDNSProperties,
    RegisterCNAMEonRoute53,
    CreateDistribution,
    ChangeRoute53ARecordToCF
], function (err) {
    if (err) {
        callback(err);
    }
    callback(null, 'Works!');
});    
};

function ChangeRoute53ARecordToCF(callback) {
    
    console.log("-------------------------ChangeRoute53ARecordToCF-------------------------"); 
    var params = {
        ChangeBatch: {
            Changes: [
               {
                   Action: "UPSERT", 
                   ResourceRecordSet: {
                       AliasTarget: {
                           DNSName: dataCloudfrontCallback.DomainName, 
                           EvaluateTargetHealth: false, 
                           HostedZoneId: "Z2FDTNDATAQYW2"//this is hardcoded. It's always this hostedzone.Probably the one that solves in the IP of CF balancer, I don't know.
                       }, 
                       Name: event.DomainName,                        
                       //TTL: 60, --need to take it off, if not, will get a "Invalid Input" error.
                       Type: "A"
                   }
               }
            ], 
            Comment: "WebServer on ElasticBeanstalk. This came from Lucas Schoch's Lambda."
        }, 
        HostedZoneId: event.HostedZoneId
    }; 

    route53.changeResourceRecordSets(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            callback(null);            
        }                
    });
}

function CreateDistribution(callback) {
    sleep(240000);//needed because there's no wait.for method to wait for SSL be validated (I'll change it in the future to schedule another lambda that will check if it's ready).
    //Cert. Mngr. usually updates it in less than 2 minutes. I'll use 4. The Lambda function timeout need to be configured to 5 minutes. It should take 4:30.

    console.log("-------------------------CreateDistribution-------------------------"); 
    var date = new Date();
    var current_hour = date.getHours();
    var params = {
        DistributionConfigWithTags: {
            DistributionConfig: { 
                CallerReference: event.DomainName + ' - ' + current_hour, /* -----------------------------------------------required */
                Comment: 'Generated by Lambda - SSL - WebSites WM Platform', 
                DefaultCacheBehavior: { /* required */
                    ForwardedValues: { /* required */
                        Cookies: { /* required */
                            Forward: 'all', /* required */
                        },
                        QueryString: true, /* required */
                        Headers:{
                            Quantity: 1,
                            Items: [
                              '*',
                              /* more items */
                            ]
                        }
                    },
                    MinTTL: 0, /* required */
                    TargetOriginId: 'ELB-lb-YOUR-LOAD-BALANCING', /* required */
                    TrustedSigners: { /* required */
                        Enabled:  false, /* required */
                        Quantity: 0, /* required */                       
                    },
                    ViewerProtocolPolicy: 'redirect-to-https', /* required */
                    AllowedMethods: {
                        Items: [ /* required */
                          'GET', 'HEAD', 'POST', 'PUT', 'PATCH', 'OPTIONS', 'DELETE',
                          /* more items */
                        ],
                        Quantity: 7, /* required */
                        //CachedMethods: {
                        //    Items: [ /* required */
                              
                        //      /* more items */
                        //    ],
                        //    Quantity: 0 /* required */
                        //}
                    },
                    Compress: false,
                    DefaultTTL: 86400,
                    MaxTTL: 31536000,
                    SmoothStreaming: false
                },
                Enabled: true, /* required */
                Origins: { /* required */
                    Quantity: 1, /* required */
                    Items: [
                      {
                          DomainName: 'lb-YOUR-LOAD-BALANCING.sa-east-1.elb.amazonaws.com', /* required */
                          Id: 'ELB-lb-YOUR-LOAD-BALANCING', /* required */
                          //CustomHeaders: {
                          //    Quantity: 0, /* required */
                          //    Items: [                                
                          //      /* more items */
                          //    ]
                          //},
                          CustomOriginConfig: {
                              HTTPPort: 80, /* required */
                              HTTPSPort: 443, /* required */
                              OriginProtocolPolicy: 'http-only', /* required */
                              OriginKeepaliveTimeout: 5,
                              OriginReadTimeout: 30,
                              OriginSslProtocols: {
                                  Items: [ /* required */
                                    'TLSv1', 'TLSv1.1', 'TLSv1.2'
                              /* more items */
                                  ],
                                  Quantity: 3 /* required */
                              }
                          },
                          OriginPath: ''
                      },
                /* more items */
                    ]
                },
                Aliases: {
                    Quantity: 2, /* required */
                    Items: [
                      '*.'+ event.DomainName, event.DomainName,
                      /* more items */
                    ]
                },
                CacheBehaviors: {
                    Quantity: 0, /* required */                    
                },
                HttpVersion: 'http2',
                IsIPV6Enabled: true,
                PriceClass: 'PriceClass_All',
                ViewerCertificate: {
                    ACMCertificateArn: dataRequested.CertificateArn,
                    CloudFrontDefaultCertificate: false,
                    MinimumProtocolVersion: 'TLSv1.1_2016',
                    SSLSupportMethod: 'sni-only'
                }
            },
            Tags: { /* required */
                Items: [
                  {
                      Key: 'Name', /* required */
                      Value: event.DomainName
                  },
                  /* more items */
                ]
            }
        }
    };
    cloudfront.createDistributionWithTags(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            dataCloudfrontCallback = data;
            callback(null);            
        }       
    });
}

function RegisterCNAMEonRoute53(callback) {
    
    console.log("-------------------------RegisterCNAMEonRoute53-------------------------"); 
    var params = {
        ChangeBatch: {
            Changes: [
               {
                   Action: "CREATE", 
                   ResourceRecordSet: {
                       Name: dataHostedZoneValidationProperties.Name,
                       ResourceRecords: [
                          {
                              Value: dataHostedZoneValidationProperties.Value
                          }
                       ], 
                       TTL: 60, 
                       Type: dataHostedZoneValidationProperties.Type
                   }
               }
            ], 
            Comment: "Certificate Manager Created by Lucas Schoch's Lambda. :)"
        }, 
        HostedZoneId: event.HostedZoneId
    };
    route53.changeResourceRecordSets(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            callback(null);            
        }       
    });
}

function DescribeCertificateToGetDNSProperties(callback) {
    
    console.log("-------------------------DescribeCertificateToGetDNSProperties-------------------------"); 
    sleep(5000);//needed because there's no wait.for method to wait for resource record to be available.

    var params = {
        CertificateArn: dataRequested.CertificateArn 
    };
    acm.describeCertificate(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);       
            dataHostedZoneValidationProperties = data.Certificate.DomainValidationOptions[0].ResourceRecord;//contem Name - Type - Value  
            console.log(data.Certificate.DomainValidationOptions[0]);       
            console.log(dataHostedZoneValidationProperties.ResourceRecord);       
            callback(null);            
        }       
    });
}

function GetAndValidateRoute53Existence(callback) {
    console.log("-------------------------GetAndValidateRoute53Existence-------------------------"); 
    var params = {
        Id: event.HostedZoneId
    };
    route53.getHostedZone(params, function(err, data) {
        if (err) 
        {
            console.log(err, err.stack);
            callback(err);
        }
        else     
        {
            console.log(data);         
            console.log(data.HostedZone);         
            if (data.HostedZone !== 'undefined') {
                dataHostedZone = data.HostedZone;
                event.DomainName = dataHostedZone.Name.slice(0, -1);
                callback(null);
            }
            else {
                callback('HostedZone não existente no Route53');
            }
        }
    });
}

function RequestCertificate(callback) {
    console.log("-------------------------RequestCertificate-------------------------"); 
    var params = {
        DomainName: event.DomainName, /* required */
        SubjectAlternativeNames: [
          '*.'+event.DomainName
        ],
        ValidationMethod: 'DNS'
    };
    acm.requestCertificate(params, function(err, data) {
        if (err) {
            console.log(err, err.stack); // an error occurred
            callback(err);
        }
        else     {
            dataRequested = data;
            console.log(data);    
            callback(null);
        }
    });
}

function AddTagToCertificate(callback) {
    console.log("-------------------------AddTagToCertificate-------------------------"); 
    var params = {
        CertificateArn: dataRequested.CertificateArn, /* required */
        Tags: [ /* required */
          {
              Key: 'Name', /* required */
              Value: event.DomainName
          },
          /* more items */
        ]
    };
    acm.addTagsToCertificate(params, function(err, data) {
        if (err) {
            console.log(err, err.stack); // an error occurred
            callback(err);
        }
        else{
            console.log(data);           // successful response
            callback(null);
        }
    });
}
